<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>InfiniteRefactor.Infrastructure.Examples.MetadataAndSwagger</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InfiniteRefactor.Infrastructure/InfiniteRefactor.Infrastructure.csproj" />
  </ItemGroup>
</Project>
