<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>InfiniteRefactor.Infrastructure.Examples.BatchQuery</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/InfiniteRefactor.Infrastructure/InfiniteRefactor.Infrastructure.csproj" />
  </ItemGroup>
</Project>
